[package]
name = "appimage-pkg"
version = "0.1.0"
edition = "2024"

[dependencies]
clap = { version = "4.5.49", features = ["cargo", "derive"] }
serde = { version = "1.0.228", features = ["derive"] }
shellexpand = { version = "3.1.1", features = ["full"] }
toml = "0.9.8"
